// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCSX2Wg5LQFh0LSIJ_SzQS_nRvPs1O_RUE',
    appId: '1:560505393019:web:3c09a7c6a071c8b282b7de',
    messagingSenderId: '560505393019',
    projectId: 'getxtexts',
    authDomain: 'getxtexts.firebaseapp.com',
    storageBucket: 'getxtexts.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDyPxeQ2hOYRADmJnyeSWLBJF7njvOITd4',
    appId: '1:560505393019:android:4ad23854d0952b4a82b7de',
    messagingSenderId: '560505393019',
    projectId: 'getxtexts',
    storageBucket: 'getxtexts.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8yPFH4xCIHCa3hrPIMJa1xXKwK-CTj-E',
    appId: '1:560505393019:ios:06f33dbd5924314e82b7de',
    messagingSenderId: '560505393019',
    projectId: 'getxtexts',
    storageBucket: 'getxtexts.appspot.com',
    iosBundleId: 'com.example.getxPro',
  );

}